fix: raise an error when target is found in playbook

diff --git a/tools/bluebanquise-playbook b/tools/bluebanquise-playbook
--- a/tools/bluebanquise-playbook
+++ b/tools/bluebanquise-playbook
@@ -50,9 +50,9 @@ fi
 
 playbook_yml="${ANSIBLE_CONFIG}/playbooks/${playbook}.yml"
 if [[ $(grep -c 'hosts:.*{{.*target.*}}' ${playbook_yml}) -ne 0 ]]; then
-    echo -e "\e[31mWARNING: Usage of {{ target }} in hosts is deprecated."\
+    echo -e "\e[31mERROR: Usage of {{ target }} in hosts is deprecated."\
          "Please update your playbook.\e[0m"
-    sleep 3
+    exit 1
 fi
 
 ansbook_cmd=$(which ansible-playbook)
@@ -68,8 +68,7 @@ if [[ $? -ne 0 ]]; then
 fi
 
 if [[ -n "$nodeset" ]]; then
-    nodeset="$(${nodeset_cmd} -e -S, ${nodeset})"
-    target="--limit ${nodeset} --extra-vars target=${nodeset}"
+    target="--limit $(${nodeset_cmd} -e -S, ${nodeset})"
 fi
 
 echo "Execute: $ansbook_cmd ${playbook_yml} ${target} ${PARAMS[@]}"
